package org.cocktail.directory.server.components;

// Generated by the WOLips Templateengine Plug-in at 8 f�vr. 2007 16:39:12

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WODisplayGroup;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.foundation.NSArray;

public class AlphabeticDataFilter extends WOComponent {
	
	private static final long serialVersionUID = -1467093901437999115L;

	public WODisplayGroup displayGroup;
	public String qualifiedField;
	
	public final NSArray listLetters = new NSArray (
					new Object[] {
					"*","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"}
					);
	
	public String currentLetter;
	
	
    public AlphabeticDataFilter(WOContext context) {
        super(context);
    }
    
    public WOComponent processFilter() {
    	StringBuffer bf = new StringBuffer(qualifiedField);
    	bf.append(" caseInsensitiveLike '").append(currentLetter).append("*'");
    	displayGroup.setQualifier( EOQualifier.qualifierWithQualifierFormat(bf.toString(),null) );
    	displayGroup.updateDisplayedObjects();
    	return null;
    }
    
}