package org.cocktail.directory.server.components;

// Generated by the WOLips Templateengine Plug-in at 15 mars 2007 10:53:45

import org.cocktail.directory.eof.server.EOAccordsAvenant;
import org.cocktail.directory.eof.server.EOAccordsAvenantPartenaire;
import org.cocktail.directory.eof.server.EOAccordsContrat;
import org.cocktail.directory.impl.Directory;
import org.cocktail.directory.impl.elements.DirectoryEntity;
import org.cocktail.directory.impl.elements.FieldItem;
import org.cocktail.directory.impl.elements.LinkFieldItem;
import org.cocktail.directory.impl.pathways.Pathway;
import org.cocktail.directory.server.DirElementNotFoundException;
import org.cocktail.directory.server.NavigationInfos;
import org.cocktail.directory.server.Session;
import org.cocktail.directory.tools.DirUtilities;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;



public class DetailConvention extends WOComponent {

	private static final long serialVersionUID = -1958013170857073205L;
	
	// bindings
	private String detailItem;
	public Directory directory;
	public Pathway pathway;
	
	public EOAccordsContrat item;
	public EOAccordsAvenant aAvenant;
	
	public String typeRequestItem = NavigationInfos.REQ_SPECIFIC_ITEM;
	
	private static NSArray fieldPartPhys;
	private static NSArray fieldPartMor;
	
	private NSArray fieldItemsPartenaires;
	
	public Session session;

	
	static {
		fieldPartMor = new NSArray(new Object[]{
				new FieldItem("LNomUsuel","displayString",null,false),
				new FieldItem("LInfosContacts","infosContacts",null,true)
		});
		
		fieldPartPhys = new NSArray(new Object[]{
				new FieldItem("LNomUsuel","displayString",null,false),
				new FieldItem("LTel","telephoneIndividu",null,true),
				new LinkFieldItem("LMail","emailPrincipalIndividu",LinkFieldItem.MAILTO_LINK)
		});
		
	}
	
	
	
	public DetailConvention(WOContext context) {
        super(context);
        session = (Session)session();
        NSMutableArray fields = new NSMutableArray();
        fields.addObject( new FieldItem("LNomUsuel","displayString",null,false) );
        fields.addObject( new FieldItem("LInfosContacts","infosContacts",null,true) );
        
	}

 	public String getDetailItem() {
		return detailItem;
	}
 	
 	public String getItemIdentification() {
 		return ((DirectoryEntity)item).displayString();
 	}
 	
 	// interception de l'identifiant de l'item dont on veut le detail 
 	// -> possibilit� de construire les FieldItem parametr�s
	public void setDetailItem(String detailItem) throws DirElementNotFoundException {
		
		this.detailItem = detailItem;
		if(detailItem!=null) {
	   		Directory dir = session.getDirectory();
	   		item = (EOAccordsContrat)dir.fetchObjectWithId(session.defaultEditingContext(),detailItem);
	   	}
	   		
	   	//TODO : Gestion des erreurs en cas de ressource introuvable !!!
	  	if(item==null) {
	   		throw new DirElementNotFoundException(session,directory,detailItem);
	  	}
	}

	public NSArray listPartenairesMorAvenant() {
		NSArray obj = aAvenant.listPartenairesSecondaires( EOAccordsAvenantPartenaire.PART_PERS_MORALE );
		return DirUtilities.cleanArray(obj);
	}
	
	public NSArray listPartenairesPhysAvenant() {
		NSArray obj = aAvenant.listPartenairesSecondaires( EOAccordsAvenantPartenaire.PART_PERS_PHYSIQUE );
		return DirUtilities.cleanArray(obj);
	}

	public NSArray getFieldPartMor() {
		return fieldPartMor;
	}

	public void setFieldPartMor(NSArray fieldPartMor) {
		DetailConvention.fieldPartMor = fieldPartMor;
	}

	public NSArray getFieldPartPhys() {
		return fieldPartPhys;
	}

	public void setFieldPartPhys(NSArray fieldPartPhys) {
		DetailConvention.fieldPartPhys = fieldPartPhys;
	}
	
	
	
}