package org.cocktail.directory.server.components;

// Generated by the WOLips Templateengine Plug-in at 21 mars 2007 17:00:56

import org.cocktail.directory.eof.server.EOIndividuUlr;
import org.cocktail.directory.eof.server.EOStructureUlr;
import org.cocktail.directory.impl.Directory;
import org.cocktail.directory.impl.elements.DirectoryEntity;
import org.cocktail.directory.impl.elements.LinkFieldItem;
import org.cocktail.directory.impl.pathways.Pathway;
import org.cocktail.directory.server.Application;
import org.cocktail.directory.server.CommonDataHolder;
import org.cocktail.directory.server.DirElementNotFoundException;
import org.cocktail.directory.server.NavigationInfos;
import org.cocktail.directory.server.Session;
import org.cocktail.directory.tools.DirUtilities;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.eocontrol.EOSortOrdering;
import com.webobjects.foundation.NSArray;

import er.extensions.appserver.ERXDisplayGroup;

public class DetailGroupe extends WOComponent {

	public static final Application app = (Application) Application.application();

	// bindings
	private String detailItem;
	private NSArray summaryFieldsForMembers;

	public Directory directory;
	public Pathway pathway;

	// misc class attributes
	public EOStructureUlr item;

	public ERXDisplayGroup displayGroup;
	public boolean shouldLinkToDetails = true;
	public String typeRequestItem = NavigationInfos.REQ_SPECIFIC_ITEM;

	public Session session;

	public DetailGroupe(WOContext context) {
		super(context);
		session = (Session) session();
	}

	public String getDetailItem() {
		return detailItem;
	}

	public String getItemIdentification() {
		return ((DirectoryEntity) item).displayString();
	}

	// interception de l'identifiant de l'item dont on veut le detail
	// -> possibilit� de construire les FieldItem parametr�s
	public void setDetailItem(String aDetailItem) throws DirElementNotFoundException {

		if (aDetailItem != null) {
			if (detailItem != null) {
				if (detailItem.equals(aDetailItem)) {
					return;
				}
			}
		}
		else {
			return;
		}

		this.detailItem = aDetailItem;

		if (detailItem != null) {
			Directory dir = session.getDirectory();
			item = (EOStructureUlr) dir.fetchObjectWithId(session.defaultEditingContext(), detailItem);
			String entityNameForDisplayGroup;
			NSArray elements;
			EOSortOrdering sortOrder;
			EOIndividuUlr user = session.connectedIndividu();
			EOStructureUlr str = item;
			boolean lr = false;
			if (user != null && user.canViewListeRouge()) {
				lr = true;
			}

			if (str.hasMembres()) {
				entityNameForDisplayGroup = "IndividuUlr";
				elements = str.membres(lr);
				sortOrder = EOSortOrdering.sortOrderingWithKey("nomUsuel", EOSortOrdering.CompareAscending);
				setSummaryFieldsForMembers(employeesDirectory().getSummaryFields());
				shouldLinkToDetails = true;
			}
			else {
				entityNameForDisplayGroup = "PersonneAlias";
				elements = (NSArray) str.valueForKey("personneAliases");
				sortOrder = EOSortOrdering.sortOrderingWithKey("alias", EOSortOrdering.CompareAscending);

				LinkFieldItem linkField = new LinkFieldItem("LMailAlias", "alias", LinkFieldItem.MAILTO_LINK);
				linkField.setLinkValueId("alias");
				setSummaryFieldsForMembers(new NSArray(linkField));

				shouldLinkToDetails = false;
			}
			displayGroup = DirUtilities.createDisplayGroup(session().defaultEditingContext(), entityNameForDisplayGroup, 20);

			if (sortOrder != null) {
				displayGroup.setSortOrderings(new NSArray(sortOrder));
			}

			displayGroup.setObjectArray(elements);
		}
	}

	public Directory directoryForMembers() {
		return employeesDirectory();
	}

	private Directory employeesDirectory() {
		return app.getDirectoryWithId(CommonDataHolder.DIR_EMPLOYEES);
	}

	public NSArray getSummaryFieldsForMembers() {
		return summaryFieldsForMembers;
	}

	public void setSummaryFieldsForMembers(NSArray fields) {
		this.summaryFieldsForMembers = fields;
	}

}