package org.cocktail.directory.server.components;

// Generated by the WOLips Templateengine Plug-in at 17 janv. 2007 12:09:00

import org.cocktail.directory.eof.server.EORibfourUlr;
import org.cocktail.directory.eof.server.EOVFournisGrhum;
import org.cocktail.directory.impl.Directory;
import org.cocktail.directory.impl.elements.DirectoryEntity;
import org.cocktail.directory.impl.pathways.Pathway;
import org.cocktail.directory.server.Application;
import org.cocktail.directory.server.CommonDataHolder;
import org.cocktail.directory.server.Session;
import org.cocktail.directory.tools.DirUtilities;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;



public class DetailSupplier extends WOComponent {

	private String detailItem;
	public Directory directory;
	public Pathway pathway;
	
	// misc class attributes
	public EOVFournisGrhum item;
	public EORibfourUlr currentRib;
	public String currentLineAdress,currentAdresseWeb;
	public Session session;
	
	public String currentTelFournis,currentFaxFournis;
	
    public DetailSupplier(WOContext context) {
        super(context);
        session = (Session)session();
    }

	public String getDetailItem() {
		return detailItem;
	}

	public void setDetailItem(String detailItem) {
		this.detailItem = detailItem;
		Directory dir = session.getDirectory();
		if(detailItem!=null)
			item = (EOVFournisGrhum)dir.fetchObjectWithId(session.defaultEditingContext(),detailItem);
	}

	
 	public String getItemIdentification() {
 		return ((DirectoryEntity)item).displayString();
 	}

 	
 	
 	// Les champs descriptifs des contacts ne sont autres que les champs sommaires d'un annuaire du personnel
 	public NSArray fieldsForContact() {
 		final Application app = (Application)Application.application();
 		Directory dirEmployees = app.getDirectoryWithId(CommonDataHolder.DIR_EMPLOYEES);
 		if(dirEmployees!=null)
 			return dirEmployees.getSummaryFields();
 		else
 			return new NSArray();
 	}
 	
    // retourne la liste des contacts pour la personne morale.
 	public NSArray getContactsForSupplier() {
    	return (NSArray)DirUtilities.invokeMethod(item,"individusContactForFournis");
    }
 	
 	
 	
	
}