package org.cocktail.directory.server.components;

// Generated by the WOLips Templateengine Plug-in at 7 d�c. 2006 11:50:23

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Header extends WOComponent {

    public Header(WOContext context) {
        super(context);
    }

}