package org.cocktail.directory.server.components;

// Generated by the WebObjects Wizard Thu Jul 18 16:33:56 America/Chicago 2002

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSData;

public class InMemoryImageElement extends WOComponent {


    public InMemoryImageElement(WOContext context) {
        super(context);
    }
    
    
    
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }

    public String contentDeliveryURL() {
        return context().componentActionURL();
    }

    public WOActionResults deliverImage() {
        WOResponse response = new WOResponse();
        response.setHeader(valueForBinding("mimeType").toString(), "content-type");
        response.setContent((NSData) valueForBinding("data"));

        return response;
    }
}
