package org.cocktail.directory.server.components;

// Generated by the WOLips Templateengine Plug-in at 21 f�vr. 2007 14:07:36

import org.cocktail.directory.server.Session;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;

import er.ajax.CktlAjaxUtils;

public class MessagesViewer extends WOComponent {
	
	public static final int MSG_ERROR 			= 1;
	public static final int MSG_INFORMATION 	= 2;
	public static final int MSG_EXCEPTION 		= 3;
	
	private Exception exception;
	public Session session;
	
	private int messageType;
	private String message;
	private boolean isLinkToMain = true;
	
	public MessagesViewer(WOContext context) {
        super(context);
        session = (Session)session();
    }
       
	public void appendToResponse(WOResponse response, WOContext context) {

		super.appendToResponse(response, context);
		CktlAjaxUtils.addStylesheetResourceInHead(context, response, "app", "css/style.css");

	}

    public String errorMessage() {
    	return exception !=null ? exception.getMessage() : session.getLocalizedString("TUndefinedError");
    }

	public Exception getException() {
		return exception;
	}

	public void setException(Exception exception) {
		this.exception = exception;
		setMessageType(MSG_EXCEPTION);
	}
	

	public boolean isError() {
		return messageType == MSG_ERROR;
	}
	
	public boolean isException() {
		return messageType == MSG_EXCEPTION;
	}
	
	public boolean isInformation() {
		return messageType == MSG_INFORMATION;
	}
	
	public String divClass() {
		if(isError())
			return "error";
		else
		if(isInformation())
			return "browser";
		else
			return null;
	}
	
	public boolean isStateless() {
		return true;
	}

	public int getMessageType() {
		return messageType;
	}

	public void setMessageType(int messageType) {
		this.messageType = messageType;
	}
	
    public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public boolean isLinkToMain() {
		return isLinkToMain;
	}

	public void setLinkToMain(boolean isLinkToMain) {
		this.isLinkToMain = isLinkToMain;
	}

}