package org.cocktail.directory.server.components;


import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at 10 sept. 2008 09:42:42
public class PasswordEtudiant extends com.webobjects.appserver.WOComponent {
    public PasswordEtudiant(WOContext context) {
        super(context);
    }
}